#!/bin/zsh
set -e

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array

# Remove all stacks from the Dock
defaults write com.apple.dock persistent-others -array

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

killall Dock

echo 'Configured Dock preferences'
