#
# Executes commands at the start of an interactive session.
#
# Customize to your needs...

# Load zsh customizations
for f in ~/.zsh/*; do source $f; done

# Add ~/bin to PATH
export PATH="$HOME/bin:$PATH"
export GPG_TTY=$(tty)