#!/bin/zsh
set -e

# Set zsh as default shell
sudo dscl . -create /Users/$USER UserShell $(brew --prefix)/bin/zsh

# Symlink dot/* into home directory as hidden files
for f in $(ls -d ~/.dotfiles/dot/*); do ln -sfn $f ~/.$(basename $f); done

# Symlink files/* into home directory as regular files
for f in $(ls -d ~/.dotfiles/files/*); do ln -sfn $f ~/$(basename $f); done

# Set preferences using defaults write
for f in $(find ~/.dotfiles/preferences -type f); do source $f; done

# If running outside of the context of Strap
if [ -z "$STRAP_GITHUB_USER" ]; then
  brew bundle check --global || brew bundle --global
  ~/.dotfiles/script/strap-after-setup
fi
